import streamlit as st
from src.marketing_data import get_latest_price
import os
from src.llm import prompt_to_text

st.set_page_config(page_title="AI Trading Agent Demo", layout="centered")

st.title("AI Trading Agent — Demo")

symbol = st.text_input("Symbol", value="AAPL")
if st.button("Get latest price"):
    with st.spinner("Fetching price..."):
        price = get_latest_price(symbol)
        if price is None:
            st.warning(f"No price available for {symbol}")
        else:
            st.success(f"Latest price for {symbol}: ${price:.2f}")

st.markdown("---")
st.write("This demo reads from your Alpaca API (set ALPACA_API_KEY and ALPACA_SECRET_KEY in `.env`).")

# LLM chat section
st.header("LLM Assistant")
st.write("Ask the integrated OpenAI LLM a question. Responses are generated by the model configured via `OPENAI_API_KEY`.")

prompt = st.text_area("Prompt", height=120)
if st.button("Ask LLM"):
    if not os.getenv("OPENAI_API_KEY"):
        st.error("OpenAI API key not found. Set OPENAI_API_KEY in your .env file or environment.")
    elif not prompt or not prompt.strip():
        st.warning("Please enter a prompt first.")
    else:
        with st.spinner("Contacting LLM..."):
            try:
                resp = prompt_to_text(prompt)
                st.success("LLM response")
                st.write(resp)
            except Exception as e:
                st.error(f"LLM request failed: {e}")
